name: CD workflow
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure Git User
        run: |
          git config --global user.name "Xavi Masvidal"
          git config --global user.email "masvidal.xavi@gmail.com"  
      - name: Deploy
        run: npm run deploy
