name: CD workflow
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Use SSH key
        run: |
          git config --global user.name "cd-user"
          git config --global user.email "cd-user@my-app.com"  
      - name: Deploy
        run: npm run deploy -- --repo git@github.com:xmasvidal/gh-pages-auto-deploy.git
